---
apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-fe-configmap
data:
  application.yaml: |
    zuul:
      routes:
        mec-developer: /mec-developer/**
      sensitive-headers:

    # disable netflix eurkea since it's not used for service discovery
    ribbon:
      eureka:
        enabled: false
      ReadTimeout: 60000
      ConnectTimeout: 60000

    server:
      port: 8080
      servlet:
        session:
          timeout: 1200
      session:
        cookie:
          name: DEVELOPERSESSIONID

    spring:
      http:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB

    APPLICATION_ID: openMec
    service_description:
      # name of the declaring microservice
      name: developer-fe
      version: 1.0.0
      environment: development
    servicecomb:
      service:
        registry:
          address: http://service-center:30100
        rest:
          address: 0.0.0.0:8080
          servlet:
            urlPattern: /cse/*
      tracing:
        enabled: false
      uploads:
        directory: /developer-fe
        maxSize: 10M

    login_page_url: https://auth.edgegallery.org/
    auth_server: http://user-mgmt-svc:8067/
    security:
      oauth2:
        sso:
          login-path: /login
        client:
          client-id: developer-fe
          client-secret: 123456
          user-authorization-uri: ${auth_server}/oauth/authorize
          access-token-uri: ${auth_server}/oauth/token
        resource:
          jwt:
            key-uri: ${auth_server}/oauth/token_key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-fe
  namespace: default
  labels:
    app: developer-fe
spec:
  selector:
    matchLabels:
      app: developer-fe
  replicas: 1
  template:
    metadata:
      labels:
        app: developer-fe
    spec:
      containers:
        - name: developer-fe
          image: edgegallery/developer-fe:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: developer-fe-config
              mountPath: /usr/app/configs/application.yaml
              subPath: application.yaml
      volumes:
        - name: developer-fe-config
          configMap:
            name: developer-fe-configmap
            items:
              - key: application.yaml
                path: application.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: developer-fe-svc
  labels:
    svc: developer-fe-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: developer-fe
